### ISSUE TITLE
Hope to add support for chunk version 7

### ISSUE THREAD

**Issue by Northern-OceanS** [BluCodeGH/bedrock#4]
This is a great project! But when I run the code, it threw an error "NotImplementedError: Unexpected chunk version 7 at chunk -10 51". I understand it's because you didn't implement the old chunk versions of minecraft worlds, so I hope that you can also add support for these chunk versions ^_^ Thank you.

**Comment by BluCodeGH** [comment]
This library is relatively simple and does not have any support for different chunk representations. It only works on many modern chunk versions because they use extremely similar internal representations. Adding support for a wide variety of versions is out of scope for this library; I suggest you look into MCEdit or the Amulet Project for wider version support.
